name: Unit Tests

on:
  push:
    branches: [main, task-1, task-2, task-3]
  pull_request:
    branches: [main, task-1, task-2, task-3]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Ensure tests folder exists
        run: |
          if [ ! -d "tests" ]; then
            echo "❌ 'tests' folder not found!"
            exit 1
          fi

      - name: Run tests
        run: |
          pytest tests/ --verbose
